---
name: Dockerfile Update
# From: https://github.com/rez0n/actions-github-release
# From: https://github.com/ludeeus/dockerfile-updater
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2 * * *'
# push:
#   branches: [main]
#   paths:
#     - "**/Dockerfile"
jobs:
  update-dockerfile-deps:
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest release of Micro-Editor
        uses: rez0n/actions-github-release@main
        id: mciro_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "zyedidia/micro"
          type: "latest"

      - uses: actions/checkout@v2.4.0

      - name: Update Dockerfile
        uses: ludeeus/dockerfile-updater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "⚓ chore(deps): update dockerfile deps."
          args: "micro=${{ steps.micro_release.outputs.release }}"
