---
name: Validate JSON
# From: https://github.com/OrRosenblatt/validate-json-action

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.json'
# push:
#   branches: [ main ]
#   paths:
#     - 'config/**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /.github/schema.json
          INPUT_JSONS: /config/settings.json,/config/bindings.json
